"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.VehicleRoutes = exports.UserRoutes = exports.VotersRoutes = exports.LeaderRoutes = exports.CandidatesRoutes = exports.ProposalRoutes = exports.AuthRoutes = void 0;
var auth_1 = require("./auth");
Object.defineProperty(exports, "AuthRoutes", { enumerable: true, get: function () { return auth_1.AuthRoutes; } });
var proposalRoutes_1 = require("./proposalRoutes");
Object.defineProperty(exports, "ProposalRoutes", { enumerable: true, get: function () { return proposalRoutes_1.ProposalRoutes; } });
var CandidatesRoutes_1 = require("./CandidatesRoutes");
Object.defineProperty(exports, "CandidatesRoutes", { enumerable: true, get: function () { return CandidatesRoutes_1.CandidatesRoutes; } });
var LeadersRoutes_1 = require("./LeadersRoutes");
Object.defineProperty(exports, "LeaderRoutes", { enumerable: true, get: function () { return LeadersRoutes_1.LeaderRoutes; } });
var VotersRoutes_1 = require("./VotersRoutes");
Object.defineProperty(exports, "VotersRoutes", { enumerable: true, get: function () { return VotersRoutes_1.VotersRoutes; } });
var usersRoutes_1 = require("./usersRoutes");
Object.defineProperty(exports, "UserRoutes", { enumerable: true, get: function () { return usersRoutes_1.UserRoutes; } });
var VehiclesRoutes_1 = require("./VehiclesRoutes");
Object.defineProperty(exports, "VehicleRoutes", { enumerable: true, get: function () { return VehiclesRoutes_1.VehicleRoutes; } });
