"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.VehicleEntity = exports.MunicipalityEntity = exports.DepartmentEntity = exports.VotersEntity = exports.UserEntity = exports.LeaderEntity = exports.CandidateEntity = exports.ProposalEntity = void 0;
var proposalsEntity_1 = require("./proposalsEntity");
Object.defineProperty(exports, "ProposalEntity", { enumerable: true, get: function () { return proposalsEntity_1.ProposalEntity; } });
var candidateEntity_1 = require("./candidateEntity");
Object.defineProperty(exports, "CandidateEntity", { enumerable: true, get: function () { return candidateEntity_1.CandidateEntity; } });
var leadersEntity_1 = require("./leadersEntity");
Object.defineProperty(exports, "LeaderEntity", { enumerable: true, get: function () { return leadersEntity_1.LeaderEntity; } });
var usersEntity_1 = require("./usersEntity");
Object.defineProperty(exports, "UserEntity", { enumerable: true, get: function () { return usersEntity_1.UserEntity; } });
var votersEntity_1 = require("./votersEntity");
Object.defineProperty(exports, "VotersEntity", { enumerable: true, get: function () { return votersEntity_1.VotersEntity; } });
var departmentsEntity_1 = require("./departmentsEntity");
Object.defineProperty(exports, "DepartmentEntity", { enumerable: true, get: function () { return departmentsEntity_1.DepartmentEntity; } });
var municipalitiesEntity_1 = require("./municipalitiesEntity");
Object.defineProperty(exports, "MunicipalityEntity", { enumerable: true, get: function () { return municipalitiesEntity_1.MunicipalityEntity; } });
var vehiclesEntity_1 = require("./vehiclesEntity");
Object.defineProperty(exports, "VehicleEntity", { enumerable: true, get: function () { return vehiclesEntity_1.VehicleEntity; } });
